language: go
go: 1.8.1
install:
  - make setup
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gem install fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
