language: go
go: 1.8.1
install: make setup
script: make ci
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - gem install fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
