language: go
go: '1.11.x'
addons:
  apt:
    packages:
      - snapd
env:
  - PATH=/snap/bin:$PATH GO111MODULE=on
install:
  - make setup
  - npm install -g prettier
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make static
  - test -n "$TRAVIS_TAG" && sudo snap install snapcraft --classic
  - test -n "$TRAVIS_TAG" && openssl aes-256-cbc -K $encrypted_8582487a7970_key -iv $encrypted_8582487a7970_iv -in snap.login.enc -out snap.login -d
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: www/public
    target_branch: master
    repo: getantibody/getantibody.github.io
    verbose: true
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
notifications:
  email: false
