language: go
go: 1.7.4
install: make setup
script: make ci
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - go get github.com/goreleaser/goreleaser
  - gem install fpm
  - test -n "$TRAVIS_TAG" && goreleaser
notifications:
  email: false
