language: go
go: 1.9
install:
  - make setup
  - npm install -g prettier
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gem install fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
  - make static
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: getantibody/getantibody.github.io
  local_dir: ./dist/getantibody.github.io
  target_branch: master
  on:
    tags: true
notifications:
  email: false
