language: go
go: 1.7.4
install:
  - go get github.com/Masterminds/glide
  - go get github.com/pierrre/gotestcover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - glide install
script: gotestcover -race -coverprofile=coverage.out $(glide novendor)
after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - test ! -z "$TRAVIS_TAG" && curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash
notifications:
  email: false
