language: go
go: 1.9
install: make setup
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    before_script: gem install fpm
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
