language: go
go: 1.7.4
install:
  - go get github.com/Masterminds/glide
  - go get github.com/pierrre/gotestcover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - glide install
script: gotestcover -race -coverprofile=coverage.out $(glide novendor)
after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
  - test -n "$TRAVIS_TAG" && gem install fpm && go get github.com/goreleaser/goreleaser && git status -sb && goreleaser
notifications:
  email: false
