language: go
go: 1.7.3
install:
  - go get github.com/Masterminds/glide
  - go get github.com/pierrre/gotestcover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - glide install
script: gotestcover -race -coverprofile=coverage.out $(glide novendor)
after_success:
  - goveralls -coverprofile=coverage.out -service=circle-ci -repotoken="$COVERALLS_TOKEN"
  - test ! -z "$TRAVIS_TAG" && ./scripts/release.sh
notifications:
  email: false
