[[constraint]]
  name = "github.com/caarlos0/gohome"
  version = "2.0.0"

[[constraint]]
  name = "github.com/getantibody/folder"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/kingpin"
